repo: "pretty-products"
canvasCourse: "web-design-1"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css

html:
  - path: "index.html"
    outline: false
    hasNot:
      - selector: "h1"
        message: "This isn’t a full webpage, just a small section, so starting at `<h2>` makes sense."
    search:
      - "Favourite"
      - "Share"
      - "Add to"
      - "cart"
      - "Crystal"
      - "Shiny, glowy and make great sounds."
      - "Diamond"
      - "Diamonds sparkle in all shapes, sizes & clarities."
      - "Gem"
      - "Lots of bright, wonderful colours—and shapes."
      - "Jewel"
      - "The root word of jewellery, so ya know it’s gorg’"
      - "Pearl"
      - "Beautifly pearlescent circles created inside living creatures."
      - "Rock"
      - "Who doesn’t love a good, plain, ol’ rock now & then."
      - "Ruby"
      - "If you love dazzling red—this is the one!"
      - "Sapphire"
      - "Blue for you. Blue is blue. Yay, blue."

css:
  - path: "css/main.css"
    has:
      - ["html", "font-family", "Karma, serif"]
      - ["html", "line-height", "1.5"]
    search:
      - "display: grid"
      - "display: flex"
      - "justify-content"
      - "align-items"
      - "gap"
      - "padding"
      - "margin"
      - "background-color"
      - "color"
      - "font-family"
      - "font-weight"
      - "Oswald, sans-serif"

screenshots:
  - path: "index.html"
    sizes: [800]

functionality:
  - path: "index.html"
    label: "Accessibility"
    tests:
      - |
        /** Double check all links have unique inner text or ARIA labels. **/
        const links = $$("a");
        let linkText = []
        let uniqText = false;
        [].forEach.call(links, (elem) => {
          let text = elem.innerText.trim() + (elem.getAttribute("aria-label") || "").trim();
          linkText.push(text.replace(/\s*/, ''));
        });
        uniqText = new Set(linkText);
        if (uniqText.size != linkText.length) {
          fail("Some links have duplicate content without unique labels.")
        }
        pass();
